### ISSUE TITLE
Cannot register machine as KVM host upon deployment

### ISSUE THREAD

**Issue by cpg1111** [maas/ansible-collection#13]
When deploying a machine, you have the option of registering the host as a VM host. This cannot be done via the collection as the deployment parameters for the instance module do not allow you to set this parameter currently.

**Comment by skatsaounis** [comment]
Fixed with #32 . There was a typo in the kvm host deploy parameter name (`install_kwm`), which was fixed [here](https://github.com/maas/ansible-collection/pull/32/files#diff-c117690b4c495bf6e1f878bcb85e62da2b2bcbc7efca94c609f1227bfa42135fL325-R329).
